### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by brauliobo** [ndbroadbent/turbo-sprockets-rails3#100]
```
Errno::ENAMETOOLONG: File name too long @ rb_sysopen - /home/braulio/noosfero/cirandas/public/assets/assets/assets/assets/assets/assets/assets/javascripts/sign_up_passw
ord_rate-1269600d30c0f64e9bfd3c777de384bc-1269600d30c0f64e9bfd3c777de384bc-1269600d30c0f64e9bfd3c777de384bc-1269600d30c0f64e9bfd3c777de384bc-1269600d30c0f64e9bfd3c777de
384bc-1269600d30c0f64e9bfd3c777de384bc-1269600d30c0f64e9bfd3c777de384bc.js+
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/asset.rb:143:in `initialize'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/asset.rb:143:in `open'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/asset.rb:143:in `write_to'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/actionpack-3.2.19/lib/sprockets/static_compiler.rb:39:in `block in write_asset'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/actionpack-3.2.19/lib/sprockets/static_compiler.rb:36:in `tap'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/actionpack-3.2.19/lib/sprockets/static_compiler.rb:36:in `write_asset'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/turbo-sprockets-rails3-0.3.14/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:42:in `block in compile'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/base.rb:219:in `block in each_logical_path'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each_entry'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/base.rb:204:in `block in each_file'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each_file'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/sprockets-2.2.2/lib/sprockets/base.rb:217:in `each_logical_path'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/turbo-sprockets-rails3-0.3.14/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:29:in `compile'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/turbo-sprockets-rails3-0.3.14/lib/turbo-sprockets/tasks/assets.rake:108:in `internal_precompile'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/turbo-sprockets-rails3-0.3.14/lib/turbo-sprockets/tasks/assets.rake:115:in `block (3 levels) in <top (required)>'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
```

**Comment by gamicklisafisherr** [comment]
This issue I have faced time to time during copying and deleting files. Please go for long path tool as it may solve your problem because it has helped me to do this in past.
