### ISSUE TITLE
rake abort

### ISSUE THREAD

**Issue by augus-zz** [ndbroadbent/turbo-sprockets-rails3#110]
``` shell
bundle exec rake assets:precompile RAILS_ENV=production --trace
** Invoke assets:precompile (first_time)
** Execute assets:precompile
/home/zql/software/ruby /home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
rake aborted!
Command failed with status (127): [/home/zql/software/ruby /home/zql/workspac...]
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:94:in `ruby'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `ruby'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/turbo-sprockets-rails3-0.3.14/lib/turbo-sprockets/tasks/assets.rake:24:in `ruby_rake_task'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/turbo-sprockets-rails3-0.3.14/lib/turbo-sprockets/tasks/assets.rake:33:in `invoke_or_reboot_rake_task'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/turbo-sprockets-rails3-0.3.14/lib/turbo-sprockets/tasks/assets.rake:50:in `block (2 levels) in <top (required)>'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/zql/software/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by augus-zz** [comment]
i fixed it,   

``` shell
/home/zql/software/ruby /home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
```

show be 

``` shell
/home/zql/software/ruby/bin/ruby /home/zql/workspace/ruby/gitlab/vendor/bundle/ruby/2.1.0/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
```
