### ISSUE TITLE
undefined method `digest' for nil:NilClass

### ISSUE THREAD

**Issue by macmartine** [ndbroadbent/turbo-sprockets-rails3#12]
I get this error on deploy. Rails 3.2.7

```
[out :: myserver.net] ** Execute assets:precompile:all
 ** [out :: myserver.net] rake aborted!
 ** [out :: myserver.net] undefined method `digest' for nil:NilClass
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.1.10/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:39:in `block in compile'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/sprockets-2.1.3/lib/sprockets/base.rb:212:in `block in each_logical_path'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/sprockets-2.1.3/lib/sprockets/base.rb:200:in `block (2 levels) in each_file'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/sprockets-2.1.3/lib/sprockets/base.rb:190:in `each'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/sprockets-2.1.3/lib/sprockets/base.rb:190:in `each_entry'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/sprockets-2.1.3/lib/sprockets/base.rb:198:in `block in each_file'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/sprockets-2.1.3/lib/sprockets/base.rb:197:in `each'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/sprockets-2.1.3/lib/sprockets/base.rb:197:in `each_file'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/sprockets-2.1.3/lib/sprockets/base.rb:210:in `each_logical_path'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.1.10/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:29:in `compile'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.1.10/lib/turbo-sprockets/tasks/assets.rake:80:in `internal_precompile'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.1.10/lib/turbo-sprockets/tasks/assets.rake:85:in `block (3 levels) in <top (required)>'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
 ** [out :: myserver.net] /home/eg/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.1.10/lib/turbo-sprockets/tasks/assets.rake:34:in `invoke_or_reboot_rake_task'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.1.10/lib/turbo-sprockets/tasks/assets.rake:40:in `block (2 levels) in <top (required)>'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
 ** [out :: myserver.net] /home/eg/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:i
 ** [out :: myserver.net] n `block (2 levels) in top_level'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/bin/rake:19:in `load'
 ** [out :: myserver.net] /apps/eg/production/shared/bundle/ruby/1.9.1/bin/rake:19:in `<main>'
 ** [out :: myserver.net] Tasks: TOP => assets:precompile:all
```

**Comment by ndbroadbent** [comment]
Hi there, sorry about that! Please update to the latest version at `0.1.13`, and this should be fixed. Cheers!
