### ISSUE TITLE
After updating - can't convert Symbol into String

### ISSUE THREAD

**Issue by fenelon** [ndbroadbent/turbo-sprockets-rails3#24]
After updating to 0.2.4 I started getting the following on precompile

```
** Invoke assets:precompile (first_time)
** Execute assets:precompile
** Invoke assets:precompile:all (first_time)
** Invoke assets:cache:clean (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:cache:clean
** Execute assets:precompile:all
rake aborted!
can't convert Symbol into String
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.4/lib/turbo-sprockets/tasks/assets.rake:78:in `join'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.4/lib/turbo-sprockets/tasks/assets.rake:78:in `block in internal_precompile'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.4/lib/turbo-sprockets/tasks/assets.rake:77:in `each'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.4/lib/turbo-sprockets/tasks/assets.rake:77:in `internal_precompile'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.4/lib/turbo-sprockets/tasks/assets.rake:108:in `block (3 levels) in <top (required)>'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/home/deployer/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.4/lib/turbo-sprockets/tasks/assets.rake:34:in `invoke_or_reboot_rake_task'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.2.4/lib/turbo-sprockets/tasks/assets.rake:49:in `block (2 levels) in <top (required)>'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/home/deployer/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/bin/rake:23:in `load'
/home/deployer/apps/myapp/shared/bundle/ruby/1.9.1/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile:all
```

**Comment by ndbroadbent** [comment]
Very sorry about that. I've released `0.2.5` which should fix the problem.

This happened because I restored the original `manifest.yml` format, but
didn't handle the old format properly. Another way to fix the problem would
have been to just delete `manifest.yml`.
