### ISSUE TITLE
Update for latest Rails

### ISSUE THREAD

**Issue by vfilesgroup** [ndbroadbent/turbo-sprockets-rails3#47]
Can you please update to make the gem 3.2.10 compatible? 

Thanks

**Comment by jarthod** [comment]
Just to add more details, here is the error I get after updating Rails:

```
rake aborted!
undefined method `compile_path?' for #<Sprockets::StaticCompiler:0x00000008ddd5d0>
gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:33:in `block in compile'
gems/sprockets-2.2.2/lib/sprockets/base.rb:219:in `block in each_logical_path'
gems/sprockets-2.2.2/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each'
gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each_entry'
gems/sprockets-2.2.2/lib/sprockets/base.rb:204:in `block in each_file'
gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each'
gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each_file'
gems/sprockets-2.2.2/lib/sprockets/base.rb:217:in `each_logical_path'
gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:29:in `compile'
gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets/tasks/assets.rake:80:in `internal_precompile'
gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets/tasks/assets.rake:87:in `block (3 levels) in <top (required)>'
gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets/tasks/assets.rake:34:in `invoke_or_reboot_rake_task'
gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets/tasks/assets.rake:40:in `block (2 levels) in <top (required)>'
```

**Comment by chrise86** [comment]
Updating to the latest version from Github will fix this:

https://github.com/ndbroadbent/turbo-sprockets-rails3/commit/1aa29210d9a257525fbd096c1093ac79b80b5be1

**Comment by jarthod** [comment]
Thanks, worked for me ;)

**Comment by chrise86** [comment]
You'll also want to be on 3.2.11 now ;)

**Comment by albertbellonch** [comment]
Does it work with Rails 3.2.11?

**Comment by jarthod** [comment]
@albertbellonch Yes it does ;)

**Comment by albertbellonch** [comment]
@jarthod Awesome, thanks!

**Comment by ndbroadbent** [comment]
Thanks all! Closing
