### ISSUE TITLE
uninitialized constant Sprockets::Base::Paths

### ISSUE THREAD

**Issue by activestylus** [ndbroadbent/turbo-sprockets-rails3#67]
I recently had to update Sprockets due to a known bug with long filenames. Was using 2.2, currently using 2.10. Since upgrading turbosprockets bombs out on me with this. Any ideas?

```
uninitialized constant Sprockets::Base::Paths
/Users/me/.rvm/gems/ruby-1.9.3-p194/bundler/gems/sprockets-cb859189faf4/lib/sprockets/base.rb:14:in `<class:Base>'
/Users/me/.rvm/gems/ruby-1.9.3-p194/bundler/gems/sprockets-cb859189faf4/lib/sprockets/base.rb:13:in `<module:Sprockets>'
/Users/me/.rvm/gems/ruby-1.9.3-p194/bundler/gems/sprockets-cb859189faf4/lib/sprockets/base.rb:11:in `<top (required)>'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets/sprockets_overrides/base.rb:1:in `require'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets/sprockets_overrides/base.rb:1:in `<top (required)>'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets-rails3.rb:11:in `require'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets-rails3.rb:11:in `block in <top (required)>'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets-rails3.rb:10:in `each'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/turbo-sprockets-rails3-0.1.16/lib/turbo-sprockets-rails3.rb:10:in `<top (required)>'
/Users/me/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
/Users/me/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
/Users/me/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
/Users/me/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
/Users/me/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
/Users/me/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
/Users/me/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
/Users/me/apps/myapp/config/application.rb:8:in `<top (required)>'
/Users/me/apps/myapp/Rakefile:5:in `require'
/Users/me/apps/myapp/Rakefile:5:in `<top (required)>'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/rake_module.rb:25:in `load'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/rake_module.rb:25:in `load_rakefile'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:589:in `raw_load_rakefile'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:89:in `block in load_rakefile'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:88:in `load_rakefile'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:72:in `block in run'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/me/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/me/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
/Users/me/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by arturtr** [comment]
Try to restart unicorn or other web-app server on your production
