### ISSUE TITLE
[0.3.8] Asset compile error

### ISSUE THREAD

**Issue by PikachuEXE** [ndbroadbent/turbo-sprockets-rails3#73]
```
Invalid CSS after "@charset "UTF-8";": expected selector or at-rule, was "<%"
       (in /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/rails_admin-0.4.9/app/assets/stylesheets/rails_admin/rails_admin.scss.erb)
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/rails_admin-0.4.9/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:3
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sass-3.2.10/lib/sass/scss/parser.rb:1145:in `expected'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sass-3.2.10/lib/sass/scss/parser.rb:1083:in `expected'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sass-3.2.10/lib/sass/scss/parser.rb:28:in `parse'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sass-3.2.10/lib/sass/engine.rb:342:in `_to_tree'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sass-3.2.10/lib/sass/engine.rb:315:in `_render'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sass-3.2.10/lib/sass/engine.rb:262:in `render'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sass-rails-3.2.6/lib/sass/rails/template_handlers.rb:106:in `evaluate'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/context.rb:197:in `block in evaluate'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/context.rb:194:in `each'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/context.rb:194:in `evaluate'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/sprockets/unprocessed_asset.rb:25:in `initialize'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/sprockets_overrides/base.rb:16:in `new'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/sprockets_overrides/base.rb:16:in `block in build_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:395:in `circular_call_protection'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/sprockets_overrides/base.rb:14:in `build_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/index.rb:94:in `block in build_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/caching.rb:58:in `cache_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/index.rb:93:in `build_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:287:in `find_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/sprockets_overrides/index.rb:14:in `find_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/sprockets_overrides/bundled_asset.rb:12:in `initialize'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/sprockets_overrides/base.rb:22:in `new'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/sprockets_overrides/base.rb:22:in `build_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/index.rb:94:in `block in build_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/caching.rb:58:in `cache_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/index.rb:93:in `build_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:287:in `find_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/sprockets_overrides/index.rb:14:in `find_asset'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:32:in `block in compile'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:341:in `block in each_logical_path'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:324:in `block (2 levels) in each_file'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:314:in `each'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:314:in `each_entry'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:322:in `block in each_file'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:321:in `each'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:321:in `each_file'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2.backport1/lib/sprockets/base.rb:335:in `each_logical_path'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:29:in `compile'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/tasks/assets.rake:102:in `internal_precompile'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/tasks/assets.rake:109:in `block (3 levels) in <top (required)>'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/tasks/assets.rake:35:in `invoke_or_reboot_rake_task'
       /tmp/build_315izh77kknco/vendor/bundle/ruby/2.0.0/gems/turbo-sprockets-rails3-0.3.8/lib/turbo-sprockets/tasks/assets.rake:50:in `block (2 levels) in <top (required)>'
```

**Comment by liquid1982** [comment]
I have the same problem right now, I can't understand if it is `rails_admin` issue (see https://github.com/sferik/rails_admin/wiki/Troubleshoot#other-issues). If I disable turbo-sprockets-rails3 the `assets:precompile` task runs smoothly.

**Comment by ndbroadbent** [comment]
Hey, I think this was caused by a recent commit. Please try updating to `0.3.9` and let me know if that fixes it.

**Comment by liquid1982** [comment]
Problem solved! Thank you very much!

**Comment by bricker** [comment]
I am still seeing a similar error, in v0.3.10:

```
$ bundle exec rake assets:precompile

rake aborted!
invalid byte sequence in UTF-8
[...]/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.10/lib/sprockets/static_non_digest_generator.rb:46:in `gsub!'
[...]/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.10/lib/sprockets/static_non_digest_generator.rb:46:in `block in generate'
[...]/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:219:in `block in each_logical_path'
[...]/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
[...]/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each'
[...]/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each_entry'
[...]/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:204:in `block in each_file'
[...]/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each'
[...]/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each_file'
[...]/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:217:in `each_logical_path'
[...]/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.10/lib/sprockets/static_non_digest_generator.rb:29:in `generate'
[...]/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.10/lib/turbo-sprockets/tasks/assets.rake:99:in `internal_precompile'
[...]/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.10/lib/turbo-sprockets/tasks/assets.rake:119:in `block (3 levels) in <top (required)>'
[...]/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.10/lib/turbo-sprockets/tasks/assets.rake:35:in `invoke_or_reboot_rake_task'
[...]/bundle/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.10/lib/turbo-sprockets/tasks/assets.rake:50:in `block (2 levels) in <top (required)>'
```
