### ISSUE TITLE
Rake aborted

### ISSUE THREAD

**Issue by kathgironpe** [ndbroadbent/turbo-sprockets-rails3#81]
I am using version 3.2.16 for Rails and 0.3.11 for turbo-sprockets-rails.

It doesn't work based on my tests.

```
time bundle exec rake assets:precompile
/Users/k/.rvm/rubies/ruby-1.9.3-p484/bin/ruby /Users/k/.rvm/gems/ruby-1.9.3-p484@project/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
/Users/k/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler.rb:284: warning: Insecure world writable dir /usr/local in PATH, mode 040777
rake aborted!
same file: /www/dir/public/assets/closure_library/closure/goog/net/crossdomainrpc_test-1b13569e9620782f423d4cd3ce931750.gif and /Volumes/www/dir/public/assets/closure_library/closure/goog/net/crossdomainrpc_test.gif
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/turbo-sprockets-rails3-0.3.11/lib/sprockets/static_non_digest_generator.rb:72:in `block in generate'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/sprockets-2.2.2/lib/sprockets/base.rb:219:in `block in each_logical_path'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/sprockets-2.2.2/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each_entry'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/sprockets-2.2.2/lib/sprockets/base.rb:204:in `block in each_file'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each_file'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/sprockets-2.2.2/lib/sprockets/base.rb:217:in `each_logical_path'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/turbo-sprockets-rails3-0.3.11/lib/sprockets/static_non_digest_generator.rb:29:in `generate'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/tasks/assets.rake:99:in `internal_precompile'
/Users/k/.rvm/gems/ruby-1.9.3-p484@project/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/tasks/assets.rake:119:in `block (3 levels) in <top (required)>'
Tasks: TOP => assets:precompile:all
```

**Comment by steponas** [comment]
I see that it's complaining about `Insecure world writable dir /usr/local in PATH, mode 040777`.
Btw, everything is working fine for me.

**Comment by kathgironpe** [comment]
@steponas You are right. It's working. Thanks! Closing this.
